### PR TITLE
Updated docs with terraform destroy

### PR DESCRIPTION
**Pull request by mgobec**
Added destroy param to the documentation

### CODE REVIEW

**Comment by mosabua** [comment]
What are the actual changes in this PR? As it stands I can not review or merge this.

**Comment by mosabua** [comment]
Is it just cb7c9a3479ec26bb7764a878d72f81571ece165f ?

**Comment by mgobec** [comment]
Yeah initially it was only [cb7c9a3](https://github.com/walmartlabs/concord-website/commit/cb7c9a3479ec26bb7764a878d72f81571ece165f).
@ibodrov should I rebase as this looks like its including a bunch of commits now?

**Comment by mosabua** [comment]
I will just pull that commit in

**Comment by mosabua** [comment]
Manually applied changes.

**Pull request closed without merging**
