### PR TITLE
updated link to quickstart

### PR DESCRIPTION
**Pull request by samhudson**
broken link to quickstart page from installation page.

### CODE REVIEW

**Comment by mosabua** [comment]
the link is not broken .. check it out at https://concord.walmartlabs.com/docs/getting-started/installation.html

**Comment by samhudson** [comment]
Hey I was referring to the link from "Getting Started" to "Configuration". The reference is relative to the install directory where it should be to the parent. "The configuration file format and available parameters described in the [Configuration](https://concord.walmartlabs.com/docs/getting-started/install/configuration.html) document."

**Comment by samhudson** [comment]
The link is contained within that statement which is routing incorrectly there's another issue with this statement also "As a next step you can create your first project as detailed in the [quickstart](https://concord.walmartlabs.com/docs/getting-started/install/quickstart.html) guide."

**Comment by mosabua** [comment]
I am not sure where you are getting and install directory existing from.. there isnt any

**Pull request closed without merging**
